# https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html
# https://docs.gitlab.com/ee/ci/unit_test_reports.html

image: python:3.9

tests:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -e src/
    - isort --check-only --profile black .
    - black --check --line-length 88 .
    - mypy ./src
    - pylint -v ./src ./tests ./tests/unit ./tests/integration
    - darglint -s sphinx -v 2 ./src
    - jinja-ninja ./src/captchamonitor/dashboard/templates
    - pytest -v --cov=src/captchamonitor/ --cov-report term-missing --junitxml=report.xml --ci-mode --ignore=tests/integration
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
      junit: report.xml

pages:
  stage: deploy
  script:
    - pip install -U sphinx
    - pip install -e src/
    - sphinx-apidoc -f -o ./docs/sphinx/ ./src/captchamonitor/
    - sphinx-build -b html ./docs/sphinx/ public
  artifacts:
    paths:
      - public
  only:
    - master