# https://docs.gitlab.com/ee/user/project/merge_requests/test_coverage_visualization.html
# https://docs.gitlab.com/ee/ci/unit_test_reports.html

image: python:latest

tests:
  stage: test
  script:
    - pip install -r requirements.txt
    - pip install -e src/
    - pip install pytest pytest-cov black
    - black --check --line-length 88 .
    - pytest -v --cov=src/captchamonitor/ --cov-report term-missing --junitxml=report.xml --ignore=tests/integration
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
      junit: report.xml