version: "2.2"

services:
  captchamonitor:
    image: captchamonitor
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      tor-browser-container:
        condition: service_healthy
      firefox-browser-container:
        condition: service_healthy
      chrome-browser-container:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/src
      - ./tests:/tests
      - /var/run/docker.sock:/var/run/docker.sock
      - tor_browser_profile_volume:/TorBrowserProfile
      - shared_tmp_volume:/tmp
    networks:
      - captchamonitor_network
    entrypoint:
      - python
      - -m
      - captchamonitor

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=captchamonitor_user
      - POSTGRES_PASSWORD=captchamonitor_test
    ports:
      - "5432:5432"
    volumes:
      - ./captchamonitor-db-data:/var/lib/postgresql/data
    networks:
      - captchamonitor_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U captchamonitor_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  tor-container:
    image: captchamonitor-tor-container:latest
    build:
      context: ./tor-container
      dockerfile: Dockerfile
    entrypoint:
      # Basically do nothing on purpose, this container will be created and run
      # as needed by the main code
      - /bin/sh

  tor-browser-container:
    image: captchamonitor-tor-browser-container:latest
    build:
      context: ./standalone-tor-browser
      dockerfile: Dockerfile
      labels:
        - VERSION=latest
    networks:
      - captchamonitor_network
    volumes:
      - shared_tmp_volume:/tmp
      - tor_browser_profile_volume:/opt/tor-browser_en-US/Browser/TorBrowser/Data/Browser/profile.default
    shm_size: '2gb'
    environment:
      SE_OPTS: "-port 4444"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444"]
      interval: 15s
      timeout: 30s
      retries: 5
    # logging:
    #   driver: none

  firefox-browser-container:
    image: selenium/standalone-firefox:latest
    volumes:
      - shared_tmp_volume:/tmp
    networks:
      - captchamonitor_network
    shm_size: '2gb'
    environment:
      SE_OPTS: "-port 4445"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4445"]
      interval: 15s
      timeout: 30s
      retries: 5
    # logging:
    #   driver: none

  chrome-browser-container:
    image: selenium/standalone-chrome:latest
    volumes:
      - shared_tmp_volume:/tmp
    networks:
      - captchamonitor_network
    shm_size: '2gb'
    environment:
      SE_OPTS: "-port 4446"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4446"]
      interval: 15s
      timeout: 30s
      retries: 5
    # logging:
    #   driver: none

networks:
  captchamonitor_network:
    driver: bridge

volumes:
  tor_browser_profile_volume:
    external: false
  shared_tmp_volume:
    external: false