version: "3"
services:

  captchamonitor:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - tor
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - CM_DB_HOST=postgres
      - CM_DB_PORT=5432
      - CM_DB_NAME=captchamonitor_db
      - CM_DB_USER=captchamonitor_user
      - CM_DB_PASSWORD=captchamonitor_test
    volumes:
      - ./src:/src
      - ./tests:/tests
    networks:
      - captchamonitor_network
    entrypoint:
      - python
      - -m
      - captchamonitor

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=captchamonitor_user
      - POSTGRES_PASSWORD=captchamonitor_test
    ports:
      - "5432:5432"
    networks:
      - captchamonitor_network

  tor:
    image: osminogin/tor-simple:latest
    restart: always
    networks:
      - captchamonitor_network


networks:
    captchamonitor_network:
      driver: bridge