version: "2.2"

services:
  captchamonitor:
    image: captchamonitor
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      tor-browser-container:
        condition: service_healthy
      firefox-browser-container:
        condition: service_healthy
      chrome-browser-container:
        condition: service_healthy
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - CM_DB_HOST=postgres
      - CM_DB_PORT=5432
      - CM_DB_NAME=captchamonitor_db
      - CM_DB_USER=captchamonitor_user
      - CM_DB_PASSWORD=captchamonitor_test
      - CM_DOCKER_NETWORK=captchamonitor_network
      - CM_DOCKER_TOR_CONTAINER_IMAGE=captchamonitor-tor-container
      - CM_DOCKER_TOR_AUTH_PASS=captchamonitor
      - CM_DOCKER_TOR_AUTH_PASS_HASHED=16:9EBDF7FF0017633A6057CB181363121298A64BC51D9DE431D788C04443
      - CM_DOCKER_TOR_BROWSER_CONTAINER_NAME=tor-browser-container
      - CM_DOCKER_TOR_BROWSER_CONTAINER_PORT=4444
      - CM_DOCKER_TOR_BROWSER_CONTAINER_PROFILE_LOCATION=/TorBrowserProfile
      - CM_DOCKER_FIREFOX_BROWSER_CONTAINER_NAME=firefox-browser-container
      - CM_DOCKER_FIREFOX_BROWSER_CONTAINER_PORT=4445
      - CM_DOCKER_CHROME_BROWSER_CONTAINER_NAME=chrome-browser-container
      - CM_DOCKER_CHROME_BROWSER_CONTAINER_PORT=4446
    volumes:
      - ./src:/src
      - ./tests:/tests
      - /var/run/docker.sock:/var/run/docker.sock
      - tor_browser_profile_volume:/TorBrowserProfile
    networks:
      - captchamonitor_network
    entrypoint:
      - python
      - -m
      - captchamonitor

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=captchamonitor_user
      - POSTGRES_PASSWORD=captchamonitor_test
    ports:
      - "5432:5432"
    networks:
      - captchamonitor_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U captchamonitor_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  tor-container:
    image: captchamonitor-tor-container
    build:
      context: ./tor-container
      dockerfile: Dockerfile
    entrypoint:
      # Basically do nothing on purpose, this container will be created and run
      # as needed by the main code
      - /bin/sh

  tor-browser-container:
    image: captchamonitor-tor-browser-container
    build:
      context: ./standalone-tor-browser
      dockerfile: Dockerfile
    networks:
      - captchamonitor_network
    volumes:
      - tor_browser_profile_volume:/opt/tor-browser_en-US/Browser/TorBrowser/Data/Browser/profile.default
    shm_size: '2gb'
    environment:
      SE_OPTS: "-port 4444"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444"]
      interval: 15s
      timeout: 30s
      retries: 5
    logging:
      driver: none

  firefox-browser-container:
    image: selenium/standalone-firefox:latest
    networks:
      - captchamonitor_network
    shm_size: '2gb'
    environment:
      SE_OPTS: "-port 4445"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4445"]
      interval: 15s
      timeout: 30s
      retries: 5
    logging:
      driver: none

  chrome-browser-container:
    image: selenium/standalone-chrome:latest
    networks:
      - captchamonitor_network
    shm_size: '2gb'
    environment:
      SE_OPTS: "-port 4446"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4446"]
      interval: 15s
      timeout: 30s
      retries: 5
    logging:
      driver: none

networks:
  captchamonitor_network:
    driver: bridge

volumes:
  tor_browser_profile_volume:
    external: false