version: "2.2"

x-logging-options: &default-logging-options
  logging:
    driver: "json-file"
    options:
        max-file: "5"
        max-size: "10m"

services:
  captchamonitor: &captchamonitor_base_service
    <<: *default-logging-options
    image: captchamonitor
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      nginx:
        condition: service_healthy
      tor-browser-container:
        condition: service_healthy
      firefox-browser-container:
        condition: service_healthy
      chrome-browser-container:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/src
      - ./tests:/tests
      - /var/run/docker.sock:/var/run/docker.sock
      - tor_browser_profile_volume:/TorBrowserProfile
      - shared_tmp_volume:/tmp
    networks:
      - captchamonitor_network

  cm-worker:
    <<: *captchamonitor_base_service
    restart: always
    entrypoint:
      - python
      - -m
      - captchamonitor
      - --worker

  cm-analyzer:
    <<: *captchamonitor_base_service
    restart: always
    entrypoint:
      - python
      - -m
      - captchamonitor
      - --analyzer

  cm-updater:
    <<: *captchamonitor_base_service
    restart: always
    entrypoint:
      - python
      - -m
      - captchamonitor
      - --updater

  cm-dashboard:
    <<: *captchamonitor_base_service
    restart: always
    entrypoint:
      - python
      - -m
      - captchamonitor
      - --dashboard

  postgres:
    <<: *default-logging-options
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${CM_DB_USER}
      POSTGRES_PASSWORD: ${CM_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./captchamonitor-db-data:/var/lib/postgresql/data
    networks:
      - captchamonitor_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $CM_DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    <<: *default-logging-options
    image: nginx
    ports:
      - "5000:80"
    volumes:
      - ./src/captchamonitor/dashboard/www:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "service", "nginx", "status"]
      interval: 60s
      timeout: 30s
      retries: 5
 
  tor-container:
    <<: *default-logging-options
    image: captchamonitor-tor-container:latest
    build:
      context: ./tor-container
      dockerfile: Dockerfile
    entrypoint:
      # Basically do nothing on purpose, this container will be created and run
      # as needed by the main code
      - /bin/sh
    healthcheck:
      test: ["CMD", "service", "tor", "status"]
      interval: 60s
      timeout: 30s
      retries: 5

  tor-browser-container:
    <<: *default-logging-options
    image: captchamonitor-tor-browser-container:latest
    build:
      context: ./standalone-tor-browser
      dockerfile: Dockerfile
      labels:
        - VERSION=latest
    networks:
      - captchamonitor_network
    volumes:
      - shared_tmp_volume:/tmp
      - tor_browser_profile_volume:/opt/tor-browser_en-US/Browser/TorBrowser/Data/Browser/profile.default
    shm_size: '2gb'
    environment:
      SE_OPTS: "-port 4444"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444"]
      interval: 15s
      timeout: 30s
      retries: 5

  firefox-browser-container:
    <<: *default-logging-options
    image: selenium/standalone-firefox:3.141.59-20210607
    volumes:
      - shared_tmp_volume:/tmp
    networks:
      - captchamonitor_network
    shm_size: '2gb'
    environment:
      SE_OPTS: "-port 4445"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4445"]
      interval: 15s
      timeout: 30s
      retries: 5

  chrome-browser-container:
    <<: *default-logging-options
    image: selenium/standalone-chrome:3.141.59-20210607
    volumes:
      - shared_tmp_volume:/tmp
    networks:
      - captchamonitor_network
    shm_size: '2gb'
    environment:
      SE_OPTS: "-port 4446"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4446"]
      interval: 15s
      timeout: 30s
      retries: 5

  brave-browser-container:
    <<: *default-logging-options
    image: captchamonitor-brave-browser-container:latest
    build:
      context: ./standalone-brave-browser
      dockerfile: Dockerfile
    networks:
      - captchamonitor_network
    volumes:
      - shared_tmp_volume:/tmp
    shm_size: '2gb'
    environment:
      SE_OPTS: "-port 4447"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4447"]
      interval: 15s
      timeout: 30s
      retries: 5

  opera-browser-container:
    <<: *default-logging-options
    image: selenium/standalone-opera:3.141.59-20210607
    volumes:
      - shared_tmp_volume:/tmp
    networks:
      - captchamonitor_network
    shm_size: '2gb'
    environment:
      SE_OPTS: "-port 4448"
    healthcheck:
      test: ["CMD-SHELL", "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4448"]
      interval: 15s
      timeout: 30s
      retries: 5
 
networks:
  captchamonitor_network:
    driver: bridge

volumes:
  tor_browser_profile_volume:
    external: false
  shared_tmp_volume:
    external: false