version: "3"
services:

  captchamonitor:
    image: captchamonitor
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - CM_DB_HOST=postgres
      - CM_DB_PORT=5432
      - CM_DB_NAME=captchamonitor_db
      - CM_DB_USER=captchamonitor_user
      - CM_DB_PASSWORD=captchamonitor_test
      - CM_DOCKER_NETWORK=captchamonitor_network
      - CM_DOCKER_TOR_CONTAINER_IMAGE=captchamonitor-tor-container
      - CM_DOCKER_TOR_AUTH_PASS=captchamonitor
      - CM_DOCKER_TOR_AUTH_PASS_HASHED=16:9EBDF7FF0017633A6057CB181363121298A64BC51D9DE431D788C04443
    volumes:
      - ./src:/src
      - ./tests:/tests
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - captchamonitor_network
    entrypoint:
      - python
      - -m
      - captchamonitor

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=captchamonitor_user
      - POSTGRES_PASSWORD=captchamonitor_test
    ports:
      - "5432:5432"
    networks:
      - captchamonitor_network

  tor-container:
    image: captchamonitor-tor-container
    build:
      context: ./tor-container
      dockerfile: Dockerfile
    entrypoint:
      # Basically do nothing on purpose
      - /bin/sh

networks:
    captchamonitor_network:
      driver: bridge